In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
from sklearn.model_selection import train_test_split

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [22]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=.2)

In [23]:
lr = LogisticRegression(max_iter=5000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9833333333333333

In [24]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9916666666666667

In [25]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9777777777777777

In [26]:
from sklearn.model_selection import KFold

In [41]:
kf = KFold(n_splits=3)
# scores = kf(RandomForestClassifier(),X_train,y_train,cv = 5)

In [42]:
for X_split,y_split in kf.split([1,2,3,4,5,6,7,8,9]):
    print(X_split,y_split)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [50]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [51]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9861111111111112

In [56]:
get_score(LogisticRegression(max_iter=5000),X_train,X_test,y_train,y_test)

0.9833333333333333

In [57]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9916666666666667

In [60]:
from sklearn.model_selection import StratifiedKFold

In [62]:
skf = StratifiedKFold(n_splits=3)

In [80]:
scores_lr = []
scores_svc = []
scores_rf = []
for X_index, y_index in skf.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[X_index], digits.data[y_index], \
    digits.target[X_index],digits.target[y_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=4000),X_train,X_test,y_train,y_test))
    scores_svc.append(get_score(SVC(),X_train,X_test,y_train,y_test))    
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))    

In [73]:
# scores_logistic = []
# scores_svm = []
# scores_rf = []

# for train_index, test_index in kf.split(digits.data,digits.target):
#     X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
#                                        digits.target[train_index], digits.target[test_index]
#     scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
#     scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
#     scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [84]:
scores_lr

[0.9248747913188647, 0.9382303839732888, 0.9232053422370617]

In [85]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [86]:
scores_rf

[0.9398998330550918, 0.9565943238731218, 0.9282136894824707]

In [87]:
# CROSS_VAL_SCORE

In [88]:
from sklearn.model_selection import cross_val_score

In [104]:
scores_l = cross_val_score(LogisticRegression(max_iter=4000),digits.data,digits.target)

In [105]:
scores_l.mean()

0.914317548746518

In [106]:
scores_sm = cross_val_score(SVC(),digits.data,digits.target)

In [117]:
scores_sm

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [114]:
scores_r = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)


In [118]:
scores_r.mean()

0.9332466728567008

In [119]:
np.average(scores_r)

0.9332466728567008